// The anti-drift test.
//
// PROTOCOL.md §7 says both repos must reproduce its golden vectors byte for byte,
// and that this test — not the prose — is what keeps the firmware and the Android
// app in sync. So the vectors below are **transcribed from the document**, not
// generated by the code under test: every expected byte array and every expected
// result code is typed out from PROTOCOL.md §7, and a decoder that quietly
// changed its mind about a field offset fails here rather than in the field.
//
// Nothing in this file round-trips through our own encoder to build an
// expectation. The one helper that constructs payloads (makeTimePayload, used for
// the cases §7 does not list) is pinned to §7.1's literal bytes by
// test_payload_builder_matches_golden_bytes below, so it cannot drift either.
#include <unity.h>

#include "core/protocol.h"
#include "core/time_model.h"

using core::DateTime;
using core::Status;
using core::SyncResult;
using core::TimeWrite;

void setUp(void) {}
void tearDown(void) {}

static int resultAsInt(SyncResult result) { return static_cast<int>(result); }

static void assertLocal(const DateTime& dt, uint16_t year, uint8_t month, uint8_t day,
                        uint8_t hour, uint8_t minute, uint8_t second) {
  TEST_ASSERT_EQUAL_UINT16(year, dt.year);
  TEST_ASSERT_EQUAL_UINT8(month, dt.month);
  TEST_ASSERT_EQUAL_UINT8(day, dt.day);
  TEST_ASSERT_EQUAL_UINT8(hour, dt.hour);
  TEST_ASSERT_EQUAL_UINT8(minute, dt.minute);
  TEST_ASSERT_EQUAL_UINT8(second, dt.second);
}

// Builds a §3.1 Time payload the way the *phone* would. Independent of
// core::protocol — the firmware has no Time encoder, and one written here would
// make the decoder tests circular. Pinned to the document by the golden-bytes
// test below.
static void makeTimePayload(uint8_t (&out)[12], uint32_t epoch, int16_t offset) {
  const uint16_t raw_offset = static_cast<uint16_t>(offset);
  out[0] = 0x01;  // proto_version
  out[1] = 0x01;  // msg_type = SetTime
  out[2] = static_cast<uint8_t>(epoch & 0xFFu);
  out[3] = static_cast<uint8_t>((epoch >> 8) & 0xFFu);
  out[4] = static_cast<uint8_t>((epoch >> 16) & 0xFFu);
  out[5] = static_cast<uint8_t>((epoch >> 24) & 0xFFu);
  out[6] = static_cast<uint8_t>(raw_offset & 0xFFu);
  out[7] = static_cast<uint8_t>((raw_offset >> 8) & 0xFFu);
  out[8] = 0x00;  // flags
  out[9] = 0x00;  // reserved
  out[10] = 0x00;
  out[11] = 0x00;
}

static TimeWrite decodeFields(uint32_t epoch, int16_t offset) {
  uint8_t payload[12];
  makeTimePayload(payload, epoch, offset);
  return core::decodeTimeWrite(payload, sizeof(payload));
}

// ── PROTOCOL.md §2.1 — identity ──────────────────────────────────────────────
//
// Typed out from the table rather than compared against themselves. A UUID that
// drifts here and nowhere else produces a watch advertising a service the phone
// is not looking for, with no other symptom at all.

void test_uuids_match_the_document(void) {
  TEST_ASSERT_EQUAL_STRING("57444159-6461-4779-b0a3-1f4c7e25d908", core::kSyncServiceUuid);
  TEST_ASSERT_EQUAL_STRING("57444101-6461-4779-b0a3-1f4c7e25d908",
                           core::kTimeCharacteristicUuid);
  TEST_ASSERT_EQUAL_STRING("57444102-6461-4779-b0a3-1f4c7e25d908",
                           core::kStatusCharacteristicUuid);
  TEST_ASSERT_EQUAL_STRING("57444103-6461-4779-b0a3-1f4c7e25d908",
                           core::kFindCharacteristicUuid);
  TEST_ASSERT_EQUAL_STRING("00002902-0000-1000-8000-00805f9b34fb", core::kCccdUuid);
}

void test_protocol_constants_match_the_document(void) {
  TEST_ASSERT_EQUAL_UINT8(0x01, core::kProtocolVersion);
  TEST_ASSERT_EQUAL_UINT8(0x01, core::kMsgTypeSetTime);
  TEST_ASSERT_EQUAL_UINT8(0x02, core::kMsgTypeFindDismiss);
  TEST_ASSERT_EQUAL_UINT8(0x81, core::kMsgTypeSyncResult);
  TEST_ASSERT_EQUAL_UINT32(12, static_cast<uint32_t>(core::kTimePayloadLength));
  TEST_ASSERT_EQUAL_UINT32(12, static_cast<uint32_t>(core::kStatusPayloadLength));
  TEST_ASSERT_EQUAL_UINT32(4, static_cast<uint32_t>(core::kFindPayloadLength));
  TEST_ASSERT_EQUAL_INT16(-840, core::kMinUtcOffsetMinutes);
  TEST_ASSERT_EQUAL_INT16(840, core::kMaxUtcOffsetMinutes);
  TEST_ASSERT_EQUAL_UINT8(0xFF, core::kBatteryPercentUnknown);
  // §3.2 flags, bit 0. The only defined bit; a second one is a PROTOCOL.md change.
  TEST_ASSERT_EQUAL_UINT8(0x01, core::kStatusFlagFindPhone);
}

// §3.2's result table. These numbers are on the wire; renumbering the enum would
// make the app read every failure as a different failure.
void test_result_codes_match_the_document(void) {
  TEST_ASSERT_EQUAL_INT(0, resultAsInt(SyncResult::Ok));
  TEST_ASSERT_EQUAL_INT(1, resultAsInt(SyncResult::BadLength));
  TEST_ASSERT_EQUAL_INT(2, resultAsInt(SyncResult::BadVersion));
  TEST_ASSERT_EQUAL_INT(3, resultAsInt(SyncResult::OutOfRange));
  TEST_ASSERT_EQUAL_INT(4, resultAsInt(SyncResult::RtcWriteFailed));
  TEST_ASSERT_EQUAL_INT(5, resultAsInt(SyncResult::BadType));
  TEST_ASSERT_EQUAL_INT(6, resultAsInt(SyncResult::Busy));
}

// ── PROTOCOL.md §5.1 — the timing numbers ────────────────────────────────────

void test_timing_constants_match_the_document(void) {
  TEST_ASSERT_EQUAL_UINT16(60, core::kSyncWindowIntervalMinutes);
  TEST_ASSERT_EQUAL_UINT16(6000, core::kAdvertiseTimeoutMs);
  TEST_ASSERT_EQUAL_UINT16(4000, core::kIdleAfterConnectTimeoutMs);
  TEST_ASSERT_EQUAL_UINT16(12000, core::kSessionCapMs);
  // §5.1's find session cap. The phone mirrors it as the floor of its ring
  // backstop, so a change here without the document changes which side ends a
  // ring that the disconnect never reached.
  TEST_ASSERT_EQUAL_UINT32(120000, core::kFindPhoneTimeoutMs);
}

// The constraint that makes those numbers what they are. The task watchdog is
// 10 s and Law 2 forbids feeding it inside a wait loop, so §5.1 resolves it by
// capping every un-fed interval at **6 s** — not at 10. Asserted as a
// relationship rather than left in a comment, because the temptation when a sync
// fails on the bench is to lengthen exactly these two numbers, and doing so turns
// a missed sync into a watchdog reset.
//
// This checks the *constants*. It deliberately does not claim to check the
// intervals themselves — an earlier version of it was named for that and did not
// do it, asserting only that each constant was below 10000, which left
// kAdvertiseTimeoutMs free to be raised to 9999 with the suite still green and
// the contract broken. What an un-fed interval actually comes to is a property of
// how the window advances through its phases, and it is driven end to end in
// test_sync_window/ — see test_no_wait_ever_reaches_the_watchdog.
void test_no_unfed_interval_may_exceed_six_seconds(void) {
  // §5.1's own number, and the tighter of the two bounds. Anything that passes
  // this is also under the 10 s watchdog with margin for the teardown tail.
  const uint16_t max_unfed_ms = 6000;
  TEST_ASSERT_LESS_OR_EQUAL_UINT16(max_unfed_ms, core::kAdvertiseTimeoutMs);
  TEST_ASSERT_LESS_OR_EQUAL_UINT16(max_unfed_ms, core::kIdleAfterConnectTimeoutMs);

  // The advertising phase is the longest un-fed interval there is: nothing has
  // been fed since the window opened. Once a central connects the watchdog is fed
  // and the phase that follows is shorter, which is the asymmetry §5.1 describes
  // and not an accident of two arbitrary numbers.
  TEST_ASSERT_LESS_OR_EQUAL_UINT16(core::kAdvertiseTimeoutMs, core::kIdleAfterConnectTimeoutMs);

  // The session cap is the belt to those two braces, so it is allowed to exceed
  // one un-fed interval — but only because the watchdog is fed on connect, and
  // only if it is long enough to contain both phases back to back. A cap shorter
  // than that would silently truncate a legitimate exchange.
  TEST_ASSERT_GREATER_OR_EQUAL_UINT16(
      static_cast<uint16_t>(core::kAdvertiseTimeoutMs + core::kIdleAfterConnectTimeoutMs),
      core::kSessionCapMs);
}

// ── PROTOCOL.md §7.1 — the golden Time vector ────────────────────────────────
//
//   Input: 2026-08-17T12:34:56Z, UTC offset +180 minutes (local 15:34:56).
//   utc_epoch_s    = 1786970096 = 0x6A82FFF0
//   utc_offset_min = 180        = 0x00B4
//   Encoded: 01 01 F0 FF 82 6A B4 00 00 00 00 00
static const uint8_t kGoldenTime[12] = {0x01, 0x01, 0xF0, 0xFF, 0x82, 0x6A,
                                        0xB4, 0x00, 0x00, 0x00, 0x00, 0x00};

void test_golden_time_vector_decodes(void) {
  const TimeWrite decoded = core::decodeTimeWrite(kGoldenTime, sizeof(kGoldenTime));

  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  TEST_ASSERT_EQUAL_UINT32(1786970096u, decoded.utc_epoch_s);
  TEST_ASSERT_EQUAL_INT16(180, decoded.utc_offset_min);
  // §7.1: "Decoded by the watch to local DateTime{ 2026, 8, 17, 15, 34, 56 }".
  assertLocal(decoded.local, 2026, 8, 17, 15, 34, 56);
}

// Pins the test-local payload builder to the document, so every constructed case
// below inherits §7.1's byte order instead of the builder's own opinion of it.
void test_payload_builder_matches_golden_bytes(void) {
  uint8_t built[12];
  makeTimePayload(built, 1786970096u, 180);
  TEST_ASSERT_EQUAL_HEX8_ARRAY(kGoldenTime, built, 12);
}

// ── PROTOCOL.md §7.2 — the golden Status vector ──────────────────────────────
//
//   Result Ok, battery 78 %, applied epoch as above, fw_build 1.
//   01 81 00 4E F0 FF 82 6A 01 00 00 00
static const uint8_t kGoldenStatus[12] = {0x01, 0x81, 0x00, 0x4E, 0xF0, 0xFF,
                                          0x82, 0x6A, 0x01, 0x00, 0x00, 0x00};

void test_golden_status_vector_encodes(void) {
  Status status;
  status.result = SyncResult::Ok;
  status.battery_percent = 78;
  status.applied_utc_epoch_s = 1786970096u;
  status.fw_build = 1;

  uint8_t encoded[12];
  for (size_t i = 0; i < sizeof(encoded); ++i) {
    encoded[i] = 0xAA;  // poison, so an unwritten byte cannot pass by accident
  }

  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(kGoldenStatus, encoded, 12);
}

// ── PROTOCOL.md §7.4 — the golden Status vector with FIND_PHONE ──────────────
//
//   §7.2's frame, sent from inside a find session. Only byte 10 differs.
//   01 81 00 4E F0 FF 82 6A 01 00 01 00
static const uint8_t kGoldenFindStatus[12] = {0x01, 0x81, 0x00, 0x4E, 0xF0, 0xFF,
                                              0x82, 0x6A, 0x01, 0x00, 0x01, 0x00};

void test_golden_find_status_vector_encodes(void) {
  Status status;
  status.result = SyncResult::Ok;
  status.battery_percent = 78;
  status.applied_utc_epoch_s = 1786970096u;
  status.fw_build = 1;
  status.flags = core::kStatusFlagFindPhone;

  uint8_t encoded[12];
  for (size_t i = 0; i < sizeof(encoded); ++i) {
    encoded[i] = 0xAA;
  }
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(kGoldenFindStatus, encoded, 12);
}

// §3.2: flags default to zero, so the §7.2 vector — which is what every sync
// window sends — is untouched by the byte gaining a meaning. Pinned separately
// from the §7.2 test so that a default that drifted to "find phone" would fail a
// test named for it rather than one named for the golden vector.
void test_status_flags_default_to_zero(void) {
  const Status fresh;
  TEST_ASSERT_EQUAL_HEX8(0, fresh.flags);
}

// §3.2: "The sender puts only the defined bit on the wire." A garbled flags field
// must not reach a receiver that has since given bit 5 a meaning.
void test_undefined_flag_bits_never_reach_the_wire(void) {
  Status status;
  status.result = SyncResult::Ok;
  status.battery_percent = 78;
  status.applied_utc_epoch_s = 1786970096u;
  status.fw_build = 1;
  uint8_t encoded[12] = {};

  status.flags = 0xFF;
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(kGoldenFindStatus, encoded, 12);

  status.flags = 0xFE;  // every bit but the defined one
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(kGoldenStatus, encoded, 12);
}

// ── PROTOCOL.md §7.5 — the golden Find vector ────────────────────────────────
//
//   The one frame the phone sends on Find — FindDismiss, reserved bytes zero:
//   01 02 00 00
static const uint8_t kGoldenFindDismiss[4] = {0x01, 0x02, 0x00, 0x00};

void test_golden_find_vector_decodes(void) {
  TEST_ASSERT_EQUAL_INT(
      resultAsInt(SyncResult::Ok),
      resultAsInt(core::decodeFindWrite(kGoldenFindDismiss, sizeof(kGoldenFindDismiss))));
}

// ── PROTOCOL.md §7.6 — Find payloads that must be rejected ───────────────────
//
// One assertion per row of the table, bytes transcribed literally.

void test_reject_find_wrong_lengths(void) {
  const uint8_t nothing[1] = {0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeFindWrite(nothing, 0)));
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeFindWrite(nullptr, 0)));
  // A null pointer with a plausible length is still nothing to parse.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeFindWrite(nullptr, 4)));

  // 01 02 00
  const uint8_t three[3] = {0x01, 0x02, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeFindWrite(three, sizeof(three))));

  // 01 02 00 00 00
  const uint8_t five[5] = {0x01, 0x02, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeFindWrite(five, sizeof(five))));

  // Every length from 0 to 20 but 4, so the check is on the number and not on
  // the three rows above happening to bracket it.
  uint8_t padded[20] = {0x01, 0x02, 0x00, 0x00};
  for (size_t length = 0; length <= sizeof(padded); ++length) {
    if (length == core::kFindPayloadLength) {
      continue;
    }
    TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                          resultAsInt(core::decodeFindWrite(padded, length)));
  }
}

void test_reject_find_wrong_version(void) {
  // 02 02 00 00
  const uint8_t payload[4] = {0x02, 0x02, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadVersion),
                        resultAsInt(core::decodeFindWrite(payload, sizeof(payload))));
}

void test_reject_find_wrong_type(void) {
  // 01 01 00 00 — a Time msg_type arriving on the Find characteristic.
  const uint8_t time_type[4] = {0x01, 0x01, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadType),
                        resultAsInt(core::decodeFindWrite(time_type, sizeof(time_type))));
  // 01 7F 00 00
  const uint8_t unknown[4] = {0x01, 0x7F, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadType),
                        resultAsInt(core::decodeFindWrite(unknown, sizeof(unknown))));
}

// §7.6's last line: the reserved bytes are ignored, as everywhere else.
void test_find_reserved_bytes_are_ignored(void) {
  const uint8_t payload[4] = {0x01, 0x02, 0xDE, 0xAD};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok),
                        resultAsInt(core::decodeFindWrite(payload, sizeof(payload))));
}

// §3.3's table is ordered like §3.1's, and for the same reason: a frame with two
// faults names the same one on both sides.
void test_find_validation_follows_the_documented_order(void) {
  // Wrong version *and* wrong type -> BadVersion.
  const uint8_t version_and_type[4] = {0x02, 0x7F, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(
      resultAsInt(SyncResult::BadVersion),
      resultAsInt(core::decodeFindWrite(version_and_type, sizeof(version_and_type))));
  // Wrong length beats every content fault.
  const uint8_t short_and_wrong[2] = {0x02, 0x7F};
  TEST_ASSERT_EQUAL_INT(
      resultAsInt(SyncResult::BadLength),
      resultAsInt(core::decodeFindWrite(short_and_wrong, sizeof(short_and_wrong))));
}

// Not from §7 — constructed from §3.2's field table — but it is what actually
// goes on the air when a write is rejected, and it proves the result code and the
// "nothing was committed" epoch reach their documented positions.
void test_rejection_status_encodes(void) {
  Status status;
  status.result = SyncResult::BadVersion;
  status.battery_percent = core::kBatteryPercentUnknown;
  status.applied_utc_epoch_s = 0;
  status.fw_build = 1;

  const uint8_t expected[12] = {0x01, 0x81, 0x02, 0xFF, 0x00, 0x00,
                                0x00, 0x00, 0x01, 0x00, 0x00, 0x00};
  uint8_t encoded[12] = {};
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(expected, encoded, 12);
}

void test_status_battery_extremes(void) {
  Status status;
  status.result = SyncResult::Ok;
  status.applied_utc_epoch_s = 0;
  status.fw_build = 0;

  uint8_t encoded[12] = {};

  status.battery_percent = 0;
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  const uint8_t empty_cell[12] = {0x01, 0x81, 0x00, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_HEX8_ARRAY(empty_cell, encoded, 12);

  status.battery_percent = 100;
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  const uint8_t full_cell[12] = {0x01, 0x81, 0x00, 0x64, 0x00, 0x00,
                                 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_HEX8_ARRAY(full_cell, encoded, 12);

  // §3.2's domain is 0..100 or 0xFF. Anything else — a garbled sample, an
  // uninitialised field — is reported as "unknown" rather than as a fourth kind
  // of value the app has to guess at.
  const uint8_t unknown_cell[12] = {0x01, 0x81, 0x00, 0xFF, 0x00, 0x00,
                                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  status.battery_percent = core::kBatteryPercentUnknown;
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(unknown_cell, encoded, 12);

  status.battery_percent = 101;
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(unknown_cell, encoded, 12);

  status.battery_percent = 200;
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(unknown_cell, encoded, 12);
}

void test_status_max_fields_encode(void) {
  Status status;
  status.result = SyncResult::Busy;
  status.battery_percent = 100;
  status.applied_utc_epoch_s = 0xFFFFFFFFu;
  status.fw_build = 0xFFFFu;

  const uint8_t expected[12] = {0x01, 0x81, 0x06, 0x64, 0xFF, 0xFF,
                                0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00};
  uint8_t encoded[12] = {};
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(expected, encoded, 12);
}

void test_status_encoder_refuses_a_short_buffer(void) {
  Status status;
  status.result = SyncResult::Ok;

  uint8_t buffer[12];
  for (size_t i = 0; i < sizeof(buffer); ++i) {
    buffer[i] = 0xAA;
  }

  // A partially written packet is worse than none: the phone would parse whatever
  // reached it as a valid Status.
  TEST_ASSERT_FALSE(core::encodeStatus(buffer, 11, status));
  for (size_t i = 0; i < sizeof(buffer); ++i) {
    TEST_ASSERT_EQUAL_HEX8(0xAA, buffer[i]);
  }

  TEST_ASSERT_FALSE(core::encodeStatus(nullptr, 32, status));

  // Exactly the payload length is enough.
  TEST_ASSERT_TRUE(core::encodeStatus(buffer, 12, status));
}

void test_status_encoder_ignores_extra_capacity(void) {
  Status status;
  status.result = SyncResult::Ok;
  status.battery_percent = 78;
  status.applied_utc_epoch_s = 1786970096u;
  status.fw_build = 1;

  uint8_t buffer[20];
  for (size_t i = 0; i < sizeof(buffer); ++i) {
    buffer[i] = 0xAA;
  }

  TEST_ASSERT_TRUE(core::encodeStatus(buffer, sizeof(buffer), status));
  TEST_ASSERT_EQUAL_HEX8_ARRAY(kGoldenStatus, buffer, 12);
  for (size_t i = 12; i < sizeof(buffer); ++i) {
    TEST_ASSERT_EQUAL_HEX8(0xAA, buffer[i]);  // wrote exactly 12 bytes, not more
  }
}

// The counterpart to test_default_time_write_is_a_rejection below, on the struct
// that actually goes on the air.
//
// §4 makes a notify with result == 0 *the* definition of a successful exchange —
// it is the one thing that resets the phone's backoff and health counters, and a
// successful connect explicitly does not count. So a Status that some early-return
// path left half-filled must not encode as a success, or the phone stops retrying
// a watch whose clock was never set. Ok would also contradict the epoch beside it:
// "written to the PCF8563" together with "nothing was committed".
void test_default_status_does_not_encode_as_success(void) {
  const Status fresh;
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Busy), resultAsInt(fresh.result));

  uint8_t encoded[12];
  for (size_t i = 0; i < sizeof(encoded); ++i) {
    encoded[i] = 0xAA;
  }
  TEST_ASSERT_TRUE(core::encodeStatus(encoded, sizeof(encoded), fresh));

  // Busy (6), battery unknown, nothing applied.
  const uint8_t expected[12] = {0x01, 0x81, 0x06, 0xFF, 0x00, 0x00,
                                0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_HEX8_ARRAY(expected, encoded, 12);
}

// ── PROTOCOL.md §7.3 — payloads that must be rejected ────────────────────────
//
// One test per row of the table, with the row's bytes transcribed literally and
// the row's expected result code.

void test_reject_empty_payload(void) {
  const uint8_t nothing[1] = {0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeTimeWrite(nothing, 0).result));
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeTimeWrite(nullptr, 0).result));
  // A null pointer with a plausible length is still nothing to parse.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeTimeWrite(nullptr, 12).result));
}

void test_reject_eleven_bytes(void) {
  // 01 01 F0 FF 82 6A B4 00 00 00 00
  const uint8_t payload[11] = {0x01, 0x01, 0xF0, 0xFF, 0x82, 0x6A, 0xB4, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeTimeWrite(payload, sizeof(payload)).result));
}

void test_reject_thirteen_bytes(void) {
  // 01 01 F0 FF 82 6A B4 00 00 00 00 00 00
  const uint8_t payload[13] = {0x01, 0x01, 0xF0, 0xFF, 0x82, 0x6A, 0xB4,
                               0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength),
                        resultAsInt(core::decodeTimeWrite(payload, sizeof(payload)).result));
}

void test_reject_wrong_protocol_version(void) {
  // 02 01 F0 FF 82 6A B4 00 00 00 00 00
  const uint8_t payload[12] = {0x02, 0x01, 0xF0, 0xFF, 0x82, 0x6A,
                               0xB4, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadVersion),
                        resultAsInt(core::decodeTimeWrite(payload, sizeof(payload)).result));
}

void test_reject_unknown_message_type(void) {
  // 01 7F F0 FF 82 6A B4 00 00 00 00 00
  const uint8_t payload[12] = {0x01, 0x7F, 0xF0, 0xFF, 0x82, 0x6A,
                               0xB4, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadType),
                        resultAsInt(core::decodeTimeWrite(payload, sizeof(payload)).result));
}

void test_reject_epoch_zero(void) {
  // 01 01 00 00 00 00 B4 00 00 00 00 00  (epoch 0 -> 1970)
  const uint8_t payload[12] = {0x01, 0x01, 0x00, 0x00, 0x00, 0x00,
                               0xB4, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(core::decodeTimeWrite(payload, sizeof(payload)).result));
}

void test_reject_offset_beyond_range(void) {
  // 01 01 F0 FF 82 6A 59 03 00 00 00 00  (offset +857)
  const uint8_t payload[12] = {0x01, 0x01, 0xF0, 0xFF, 0x82, 0x6A,
                               0x59, 0x03, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(core::decodeTimeWrite(payload, sizeof(payload)).result));
}

// A rejected write must leave nothing usable behind: §3.2 wants
// applied_utc_epoch_s reported as 0 when nothing was committed, and a caller that
// copied a rejected epoch into it would tell the phone the clock had been set.
void test_rejected_writes_yield_no_usable_fields(void) {
  const uint8_t bad_version[12] = {0x02, 0x01, 0xF0, 0xFF, 0x82, 0x6A,
                                   0xB4, 0x00, 0x00, 0x00, 0x00, 0x00};
  const TimeWrite decoded = core::decodeTimeWrite(bad_version, sizeof(bad_version));
  TEST_ASSERT_EQUAL_UINT32(0, decoded.utc_epoch_s);
  TEST_ASSERT_EQUAL_INT16(0, decoded.utc_offset_min);
  TEST_ASSERT_FALSE(core::isValid(decoded.local));
}

// A default-constructed TimeWrite must not look like a validated one.
void test_default_time_write_is_a_rejection(void) {
  const TimeWrite fresh;
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::BadLength), resultAsInt(fresh.result));
  TEST_ASSERT_FALSE(core::isValid(fresh.local));
}

// ── §3.1: flags and reserved are ignored, and that is the point ──────────────
//
// Ignoring them is what lets a v1.x sender add a field without a version bump.
// Validating them would take that away and would make the next app release look
// like a protocol break.

void test_flags_and_reserved_are_ignored(void) {
  uint8_t payload[12];
  makeTimePayload(payload, 1786970096u, 180);
  payload[8] = 0xFF;   // flags
  payload[9] = 0xDE;   // reserved
  payload[10] = 0xAD;
  payload[11] = 0xBE;

  const TimeWrite decoded = core::decodeTimeWrite(payload, sizeof(payload));
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2026, 8, 17, 15, 34, 56);
}

// ── Validation order ─────────────────────────────────────────────────────────
//
// §3.1 lists its checks in an order, and a payload with two faults has to report
// the same code on both sides or the app's diagnostic screen blames the wrong
// thing. Version outranks type, type outranks the value checks, and length
// outranks everything.

void test_validation_follows_the_documented_order(void) {
  // Wrong version *and* wrong type -> BadVersion.
  const uint8_t version_and_type[12] = {0x02, 0x7F, 0xF0, 0xFF, 0x82, 0x6A,
                                        0xB4, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(
      resultAsInt(SyncResult::BadVersion),
      resultAsInt(core::decodeTimeWrite(version_and_type, sizeof(version_and_type)).result));

  // Wrong type *and* an impossible epoch -> BadType.
  const uint8_t type_and_epoch[12] = {0x01, 0x7F, 0x00, 0x00, 0x00, 0x00,
                                      0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT_EQUAL_INT(
      resultAsInt(SyncResult::BadType),
      resultAsInt(core::decodeTimeWrite(type_and_epoch, sizeof(type_and_epoch)).result));

  // Wrong length beats every content fault.
  const uint8_t short_and_wrong[3] = {0x02, 0x7F, 0x00};
  TEST_ASSERT_EQUAL_INT(
      resultAsInt(SyncResult::BadLength),
      resultAsInt(core::decodeTimeWrite(short_and_wrong, sizeof(short_and_wrong)).result));
}

// ── The offset range, §3.1 ───────────────────────────────────────────────────

void test_offset_extremes_accepted(void) {
  // UTC+14. 2026-08-17T12:34:56Z becomes the 18th locally.
  TimeWrite decoded = decodeFields(1786970096u, 840);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  TEST_ASSERT_EQUAL_INT16(840, decoded.utc_offset_min);
  assertLocal(decoded.local, 2026, 8, 18, 2, 34, 56);

  // UTC-14. The same instant is still the 16th locally.
  decoded = decodeFields(1786970096u, -840);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  TEST_ASSERT_EQUAL_INT16(-840, decoded.utc_offset_min);
  assertLocal(decoded.local, 2026, 8, 16, 22, 34, 56);

  // Zero is an offset like any other.
  decoded = decodeFields(1786970096u, 0);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2026, 8, 17, 12, 34, 56);
}

void test_offset_one_minute_beyond_the_range_rejected(void) {
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(1786970096u, 841).result));
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(1786970096u, -841).result));
  // The extremes of the i16 field itself, which is what a byte-swapped sender
  // would produce.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(1786970096u, 32767).result));
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(1786970096u, -32768).result));
}

// The offset is a signed field, and reading it unsigned is the classic way to get
// a watch in the Americas set fourteen hours ahead instead of five behind.
void test_negative_offsets_are_read_as_signed(void) {
  const TimeWrite decoded = decodeFields(1786924800u, -300);  // 2026-08-17T00:00:00Z, UTC-5
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  TEST_ASSERT_EQUAL_INT16(-300, decoded.utc_offset_min);
  assertLocal(decoded.local, 2026, 8, 16, 19, 0, 0);
}

// ── Day, month and year boundaries crossed by the offset ─────────────────────

void test_negative_offset_pushes_into_the_previous_day(void) {
  // 2026-08-17T00:00:00Z at UTC-5 is still the 16th.
  const TimeWrite decoded = decodeFields(1786924800u, -300);
  assertLocal(decoded.local, 2026, 8, 16, 19, 0, 0);
}

void test_positive_offset_pushes_into_the_next_day(void) {
  // 2026-08-17T12:34:56Z at UTC+14 is already the 18th.
  const TimeWrite decoded = decodeFields(1786970096u, 840);
  assertLocal(decoded.local, 2026, 8, 18, 2, 34, 56);
}

void test_offset_crosses_the_year_boundary_forwards(void) {
  // 2023-12-31T23:59:59Z at UTC+1 -> 2024-01-01 00:59:59. Day, month and year all
  // roll in one step.
  const TimeWrite decoded = decodeFields(1704067199u, 60);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2024, 1, 1, 0, 59, 59);
}

void test_offset_crosses_the_year_boundary_backwards(void) {
  // 2026-01-01T00:30:00Z at UTC-1 -> 2025-12-31 23:30:00.
  const TimeWrite decoded = decodeFields(1767227400u, -60);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2025, 12, 31, 23, 30, 0);
}

// ── Leap years ───────────────────────────────────────────────────────────────

void test_leap_day_decodes(void) {
  // 2024-02-29T12:00:00Z.
  const TimeWrite decoded = decodeFields(1709208000u, 0);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2024, 2, 29, 12, 0, 0);
}

void test_day_after_the_leap_day_decodes(void) {
  // 2024-03-01T00:00:00Z.
  const TimeWrite decoded = decodeFields(1709251200u, 0);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2024, 3, 1, 0, 0, 0);
}

void test_february_in_a_common_year_has_no_29th(void) {
  // 2026-02-28T23:30:00Z at UTC+1 -> 2026-03-01 00:30:00, because 2026 has no
  // 29 February. An off-by-one in the leap rule shows up here as 29 February 2026,
  // which isValid() would then reject and the sync would fail for no visible
  // reason.
  const TimeWrite decoded = decodeFields(1772321400u, 60);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2026, 3, 1, 0, 30, 0);
}

// ── The 2020..2099 accepted window, §3.1's last validation row ───────────────

void test_range_edges_accepted(void) {
  // 2020-01-01T00:00:00Z — the first instant kMinYear allows.
  TimeWrite decoded = decodeFields(1577836800u, 0);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2020, 1, 1, 0, 0, 0);

  // 2099-12-31T23:59:59Z — the last instant kMaxYear allows.
  decoded = decodeFields(4102444799u, 0);
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::Ok), resultAsInt(decoded.result));
  assertLocal(decoded.local, 2099, 12, 31, 23, 59, 59);
}

void test_one_second_outside_the_range_rejected(void) {
  // 2019-12-31T23:59:59Z.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(1577836799u, 0).result));
  // 2100-01-01T00:00:00Z.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(4102444800u, 0).result));
}

// The range check is applied to the local time, not the UTC instant. Both of these
// are inside the window in UTC and outside it once the offset lands.
void test_offset_can_push_a_valid_instant_out_of_range(void) {
  // 2020-01-01T00:30:00Z at UTC-1 -> 2019-12-31 23:30:00.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(1577838600u, -60).result));
  // 2099-12-31T23:30:00Z at UTC+1 -> 2100-01-01 00:30:00.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(4102443000u, 60).result));
}

// §3.1 states that the u32 epoch's 2106 wrap is unreachable because kMaxYear bites
// first. Asserted rather than trusted, so nobody "fixes" the field into a u64 and
// breaks the 12-byte layout.
void test_u32_epoch_extremes_rejected(void) {
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(0xFFFFFFFFu, 0).result));
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(0u, 0).result));
  // Epoch 0 with the most negative legal offset lands in 1969: the local seconds
  // go below zero, which is the arithmetic case most likely to produce a
  // plausible-looking wrong date rather than an obvious one.
  TEST_ASSERT_EQUAL_INT(resultAsInt(SyncResult::OutOfRange),
                        resultAsInt(decodeFields(0u, -840).result));
}

int main(void) {
  UNITY_BEGIN();

  RUN_TEST(test_uuids_match_the_document);
  RUN_TEST(test_protocol_constants_match_the_document);
  RUN_TEST(test_result_codes_match_the_document);
  RUN_TEST(test_timing_constants_match_the_document);
  RUN_TEST(test_no_unfed_interval_may_exceed_six_seconds);

  RUN_TEST(test_golden_time_vector_decodes);
  RUN_TEST(test_payload_builder_matches_golden_bytes);
  RUN_TEST(test_golden_status_vector_encodes);
  RUN_TEST(test_golden_find_status_vector_encodes);
  RUN_TEST(test_status_flags_default_to_zero);
  RUN_TEST(test_undefined_flag_bits_never_reach_the_wire);
  RUN_TEST(test_golden_find_vector_decodes);
  RUN_TEST(test_reject_find_wrong_lengths);
  RUN_TEST(test_reject_find_wrong_version);
  RUN_TEST(test_reject_find_wrong_type);
  RUN_TEST(test_find_reserved_bytes_are_ignored);
  RUN_TEST(test_find_validation_follows_the_documented_order);
  RUN_TEST(test_rejection_status_encodes);
  RUN_TEST(test_status_battery_extremes);
  RUN_TEST(test_status_max_fields_encode);
  RUN_TEST(test_status_encoder_refuses_a_short_buffer);
  RUN_TEST(test_status_encoder_ignores_extra_capacity);
  RUN_TEST(test_default_status_does_not_encode_as_success);

  RUN_TEST(test_reject_empty_payload);
  RUN_TEST(test_reject_eleven_bytes);
  RUN_TEST(test_reject_thirteen_bytes);
  RUN_TEST(test_reject_wrong_protocol_version);
  RUN_TEST(test_reject_unknown_message_type);
  RUN_TEST(test_reject_epoch_zero);
  RUN_TEST(test_reject_offset_beyond_range);
  RUN_TEST(test_rejected_writes_yield_no_usable_fields);
  RUN_TEST(test_default_time_write_is_a_rejection);

  RUN_TEST(test_flags_and_reserved_are_ignored);
  RUN_TEST(test_validation_follows_the_documented_order);

  RUN_TEST(test_offset_extremes_accepted);
  RUN_TEST(test_offset_one_minute_beyond_the_range_rejected);
  RUN_TEST(test_negative_offsets_are_read_as_signed);
  RUN_TEST(test_negative_offset_pushes_into_the_previous_day);
  RUN_TEST(test_positive_offset_pushes_into_the_next_day);
  RUN_TEST(test_offset_crosses_the_year_boundary_forwards);
  RUN_TEST(test_offset_crosses_the_year_boundary_backwards);

  RUN_TEST(test_leap_day_decodes);
  RUN_TEST(test_day_after_the_leap_day_decodes);
  RUN_TEST(test_february_in_a_common_year_has_no_29th);

  RUN_TEST(test_range_edges_accepted);
  RUN_TEST(test_one_second_outside_the_range_rejected);
  RUN_TEST(test_offset_can_push_a_valid_instant_out_of_range);
  RUN_TEST(test_u32_epoch_extremes_rejected);

  return UNITY_END();
}
